### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by juliann** [datastaxdevs/appdev-week2-tiktok#126]
**Name:** Julian Nadarzy
**Email:** julian.nadarzy@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/julian-nadarzy-74b7b810/
![astra documents fixed](https://user-images.githubusercontent.com/1125748/125817499-38b7594b-e763-408f-a116-2e8c9d2a7e25.jpg)
![netlify](https://user-images.githubusercontent.com/1125748/125817555-1622eb38-03ce-45c8-ae73-57f92ad02904.jpg)
![tiktok](https://user-images.githubusercontent.com/1125748/125817572-8475b0eb-50e0-48e3-b808-f41235f5f65e.jpg)
>

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Julian Nadarzy**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/TPBquDnbRkWQyUZ54Mqh4w
