### ISSUE TITLE
[HW] Mahesh Dhavane

### ISSUE THREAD

**Issue by razor300** [datastaxdevs/appdev-week2-tiktok#142]
**Name:** Mahesh Dhavane
**Email**:  maheshdhawne2000@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/mahesh-dhavane-0aa6201ba/
**link:** https://priceless-shannon-f453be.netlify.app/#/

Attach the homework step I screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/72245057/125837544-8c0ae962-1d1c-43d7-914e-705cc1400a1c.png)
![image](https://user-images.githubusercontent.com/72245057/125837686-cfb1e8b5-020e-44aa-b54d-e2e588789bde.png)

  
Attach the homework step II screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/72245057/125839302-d2c7d5d0-4280-44a4-bdc0-45654e4c4de3.png)
![image](https://user-images.githubusercontent.com/72245057/125839407-5fa1f2cc-2676-42cc-a7c0-838ed3be0b6c.png)

**Comment by RyanWelford** [comment]
Awesome, well done Mahesh!

**Comment by HadesArchitect** [comment]
Hey **Mahesh Dhavane**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/v6dic8IhTw2OnQZ1l-yuqQ
