### ISSUE TITLE
[HW] Lee Yong Wei

### ISSUE THREAD

**Issue by fackerlee** [datastaxdevs/appdev-week2-tiktok#161]
Name: Lee Yong Wei
Email: fackerlee@gmail.com
Linkedin Profile: https://www.linkedin.com/in/yongw3i/

Attach the homework step I screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/76558523/125988807-8460d572-04e9-4ec5-abe1-93369803cfbd.png)

![image](https://user-images.githubusercontent.com/76558523/125988997-687b7ce7-5b15-486a-b67d-d4f2e851556a.png)

![image](https://user-images.githubusercontent.com/76558523/125989794-8210d895-0305-4aa8-9943-1bb7c0dfc400.png)

![image](https://user-images.githubusercontent.com/76558523/125989895-453eae34-fe8a-4389-9594-d903ed8a89ca.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/76558523/125989157-858ad685-1007-40ff-95d2-27fce3dc6e50.png)

![image](https://user-images.githubusercontent.com/76558523/125990184-7198a751-e326-4a4d-b16d-85e0b9813e05.png)

![image](https://user-images.githubusercontent.com/76558523/125990385-ca2f90f1-6908-4a04-b85c-e705cc9e4a7a.png)

**Comment by RyanWelford** [comment]
Looks like you were able to deploy successfully. Great job, Lee!

**Comment by HadesArchitect** [comment]
Hey **Lee Yong Wei**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/5HbXD0eRSj2Vc1UA9_U5Jg
