### ISSUE TITLE
[HW] Gurmehar Bakshi

### ISSUE THREAD

**Issue by gsbakshi** [datastaxdevs/appdev-week2-tiktok#165]
**Name:** Gurmehar Singh Bakshi
**Email:** greaser.bakshi@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/gsbakshi/

Attach the homework step I screenshots below:
-----------------------------------------
![Screenshot 2021-07-17 at 1 18 34 AM](https://user-images.githubusercontent.com/61559056/126014137-b6491572-f486-44b2-8400-741afbecc402.png)
![Screenshot 2021-07-17 at 1 19 07 AM](https://user-images.githubusercontent.com/61559056/126014149-4473af75-7f82-4e3b-9925-0563badbb774.png)
![Screenshot 2021-07-17 at 1 19 24 AM](https://user-images.githubusercontent.com/61559056/126014164-7deb2a58-3f76-401d-8586-9e857d2941a8.png)
![Screenshot 2021-07-17 at 1 19 37 AM](https://user-images.githubusercontent.com/61559056/126014165-60ff7df8-6ec1-4796-adf8-2c0d256b09e5.png)
![Screenshot 2021-07-17 at 1 19 43 AM](https://user-images.githubusercontent.com/61559056/126014166-82722ebb-f65c-4daa-b0b1-091b5e3f67bd.png)
![Screenshot 2021-07-17 at 1 19 55 AM](https://user-images.githubusercontent.com/61559056/126014167-f06a7804-ca5b-43d0-8caf-4a705cbeb0e8.png)

Attach the homework step II screenshots below:
-----------------------------------------
![Screenshot 2021-07-17 at 1 17 45 AM](https://user-images.githubusercontent.com/61559056/126014189-331a35d5-d33b-4c59-9f3d-729b3f28b078.png)
![Screenshot 2021-07-17 at 1 20 34 AM](https://user-images.githubusercontent.com/61559056/126014197-5820b46a-b398-4401-b1cc-2ef9ad627089.png)

Repo Link : https://github.com/gsbakshi/slam-gram
Deployed Link : https://slamgram.netlify.app/

I worked on this repo on my local machine and not on gitpod.
This repo link has the CRA readme before I updated it
https://github.com/gsbakshi/slam-gram/tree/7728a496585c0f2776c851714782cc951b1f1ebb

**Comment by hemidactylus** [comment]
Hi, congratulations! You did a very good job and added various nice touches to your TikTok clone!
Enjoy your very well deserved badge and see you on the next episode of the series!

**Comment by HadesArchitect** [comment]
Hey **Gurmehar Singh Bakshi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/BOPmJY7eQHOsmDpQ3LiSCA

**Comment by gsbakshi** [comment]
> Hi, congratulations! You did a very good job and added various nice touches to your TikTok clone!
> Enjoy your very well deserved badge and see you on the next episode of the series!

Thank you! Looking forward to it
