### ISSUE TITLE
[HW] Tizelia Norville

### ISSUE THREAD

**Issue by Zeliapooh** [datastaxdevs/appdev-week2-tiktok#175]
**Name:** Tizelia Norville
**Email:** tize_girl@live.com
**Linkedin Profile:** https://www.linkedin.com/in/tizelia-norville-3535bb201/

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/77815716/126162365-0dfa53ef-3a22-4780-b758-b238006e7154.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![Screenshot 2021-07-17 10 12 47 PM](https://user-images.githubusercontent.com/77815716/126053636-b17ec37c-94dd-4255-b35e-84a34aa2d740.png)

![Screenshot 2021-07-17 10 09 00 PM](https://user-images.githubusercontent.com/77815716/126053639-f3e37813-6a6b-433e-bb08-924b3072f3ba.png)

**Comment by hemidactylus** [comment]
Hello! You are successfully running the application in Gitpod (congratulations!), but to complete the exercise please deploy it to Netlify as instructed from step 9 onward here : https://github.com/datastaxdevs/appdev-week2-tiktok#9-connect-netlify-to-your-site
You can then re-submit the homework once it is completed. Good luck!
