### ISSUE TITLE
[HW] Michelle Greyson wk2

### ISSUE THREAD

**Issue by michellengreyson** [datastaxdevs/appdev-week2-tiktok#230]
**Name:** Michelle Greyson
**Email:** michellengreyson@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/michellengreyson/

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot (56)](https://user-images.githubusercontent.com/56977312/126558235-93644ff7-5e24-443c-94ea-f558684b4206.png)

**Comment by HadesArchitect** [comment]
Hey **Michelle Greyson**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/V9AapyJqT5elQrKqX9w1rw

**Comment by michellengreyson** [comment]
Thank you so much!
