### ISSUE TITLE
[HW] Week 2 Tiktok Clone

### ISSUE THREAD

**Issue by samarthbansal258** [datastaxdevs/appdev-week2-tiktok#244]
**Name:** Samarth Bansal
**Email:** samarth.bansal@pathways.in
**Linkedin Profile:** https://www.linkedin.com/in/samarth-bansal-06b043218/

(I added a custom video with a custom username)

Attach the homework step I screenshots below: 
-----------------------------------------
<img width="1440" alt="Screenshot 2021-07-24 at 11 06 33 AM" src="https://user-images.githubusercontent.com/86355086/126858706-74b2d489-2382-4332-bcd0-c32c8d82013e.png">

Attach the homework step II screenshots below:
-----------------------------------------
<img width="1440" alt="Screenshot 2021-07-24 at 11 13 45 AM" src="https://user-images.githubusercontent.com/86355086/126858713-033b1ccc-b1c2-43c0-bc6e-f2cd1d157a8b.png">

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Hey there Samarth, nice job getting the app running and uploading a custom video. Did you get the app fully deployed to production with Netlify? If so, please either provide your netify app link or a screenshot of the app deployed.

**Comment by samarthbansal258** [comment]
> Hey there Samarth, nice job getting the app running and uploading a custom video. Did you get the app fully deployed to production with Netlify? If so, please either provide your netify app link or a screenshot of the app deployed.

Here is the improved and updated work!
<img width="1440" alt="Screenshot 2021-07-26 at 7 44 19 PM" src="https://user-images.githubusercontent.com/86355086/127003583-978c9178-e7be-415e-900b-25b14c2bc149.png">

**Comment by HadesArchitect** [comment]
Hey **Samarth Bansal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/xcxGT5tASy6ZuQ8djXGAmw
