### ISSUE TITLE
Assignment: TikTok Clone

### ISSUE THREAD

**Issue by rabbiakhan** [datastaxdevs/appdev-week2-tiktok#55]
**Rabbia Khan**
**rabbiakhan345@gmail.com**
https://www.linkedin.com/in/biyakhan/

**Comment by SonicDMG** [comment]
Hi Rabbia, really nice job documenting all of your steps. I see you were with us for the full workshop and you got the application running locally via GitPod. Awesome. Do you have a screen from the fully deployed app in Netlify from step 1 of the homework? 
1. Complete the practice steps from this repository as described below. Make screenshots alongside the steps and show us your deployed production TikTok clone up in Netlify.
