### ISSUE TITLE
[HW] Arinjay Gangwar

### ISSUE THREAD

**Issue by arinjayg** [datastaxdevs/appdev-week2-tiktok#83]
**Name:** Arinjay Gangwar
**Email:** arinjay.gangwar100@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/arinjay-gangwar-1a3b93166/

Attach the homework step I screenshots below:
-----------------------------------------
GitPod-
<SCREENSHOTS>
 
![Screenshot 2021-07-14 212507](https://user-images.githubusercontent.com/76163860/125661901-3225692a-9be7-42f8-ab13-cdf5f99aaed6.jpg)

Running App-

![Screenshot 2021-07-14 211530](https://user-images.githubusercontent.com/76163860/125662100-5f07d002-ca01-4f9e-9cf5-00771c512639.jpg)

Netlify Deploys Page-

![Screenshot 2021-07-14 221009](https://user-images.githubusercontent.com/76163860/125662382-93712fd9-29a1-4e08-8b02-72a25a34e736.jpg)

Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Awesome job, thank you. Here's your badge -> https://api.badgr.io/public/assertions/lEQYja9WR3abvw07wtZOLQ?identity__email=arinjay.gangwar100%40gmail.com
